attention_head_size: 1
categorical_groups: {}
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_continuous_size: 8
hidden_continuous_sizes: {}
hidden_size: 16
learning_rate: 0.03
log_gradient_flow: false
log_interval: 10
log_val_interval: null
lstm_layers: 1
max_encoder_length: 1065
monotone_constaints: {}
optimizer: ranger
optimizer_params: null
output_size: 7
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 4
share_single_variable_networks: false
static_categoricals: []
static_reals:
- encoder_length
- value_center
- value_scale
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- relative_time_idx
time_varying_reals_encoder:
- relative_time_idx
weight_decay: 0.0
x_categoricals: []
x_reals:
- encoder_length
- value_center
- value_scale
- relative_time_idx
