embeddings {
  tensor_name: "agency:00001"
  metadata_path: "00001/agency\\metadata.tsv"
  tensor_path: "00001/agency\\tensors.tsv"
}
embeddings {
  tensor_name: "sku:00001"
  metadata_path: "00001/sku\\metadata.tsv"
  tensor_path: "00001/sku\\tensors.tsv"
}
embeddings {
  tensor_name: "special_days:00001"
  metadata_path: "00001/special_days\\metadata.tsv"
  tensor_path: "00001/special_days\\tensors.tsv"
}
embeddings {
  tensor_name: "month:00001"
  metadata_path: "00001/month\\metadata.tsv"
  tensor_path: "00001/month\\tensors.tsv"
}
