categorical_groups: {}
cell_type: LSTM
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_size: 10
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: null
monotone_constaints: {}
n_plotting_samples: null
n_validation_samples: null
optimizer: ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    b8uiVSgpzL8=
  eps: 1.0e-08
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    xk3t2Gl0/j8=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
rnn_layers: 2
static_categoricals: []
static_reals: []
target: value
target_lags: {}
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- value
weight_decay: 0.0
x_categoricals: []
x_reals:
- value
