backcast_loss_ratio: 1.0
context_length: 60
dropout: 0.1
expansion_coefficient_lengths:
- 3
- 7
learning_rate: 0.004
log_gradient_flow: false
log_interval: 10
log_val_interval: 1
monotone_constaints: {}
num_block_layers:
- 3
- 3
num_blocks:
- 3
- 3
optimizer: ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    CgPj5947H0E=
  eps: 1.0e-08
  method: standard
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    unaQ7dFt+UA=
  transformation: relu
prediction_length: 30
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
sharing:
- true
- true
stack_types:
- trend
- seasonality
weight_decay: 0.01
widths:
- 32
- 512
